### ISSUE TITLE
Are there any plans for header-only files or to easily integrate cmake?

### ISSUE THREAD

**Issue by Piorosen** [antirez/smallchat#15]
LMAO ><

**Comment by MZalfred** [comment]
In C++, a header-only library is one where the entire library is contained in header files. You don't have a separate **.cpp** file to compile; you just **#include** the header, and you're good to go.

**Comment by qycyfjy** [comment]
it's just a small applicaiton with single source file and only three compile flags.
It is impossible to be header-only and no reason to use cmake,

**Comment by Piorosen** [comment]
> it's just a small applicaiton with single source file and only three compile flags.
> 
> It is impossible to be header-only and no reason to use cmake,

ah!!!! thank you, my question is perfectly solved. so, this issue is closed.
