### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by moutainMan** [antirez/smallchat#23]
Brother, is there any usage documentation for this or how to deploy it?

**Comment by NO-skcaj** [comment]
I don't think it's meant to be deployed

**Comment by SaleriHQ** [comment]
You can clone the project, then use `cd smallchat && gcc smallchat.cpp -o chat` to get the executable file.

**Comment by ox776a** [comment]
You can simply use the socat command to connect to the server:

socat - tcp-connect:127.0.0.1:7711
Welcome to Simple Chat! Use /nick <nick> to set your nick.
