### ISSUE TITLE
How to use it?I ran it after make and found nothing, system is fedora38.

### ISSUE THREAD

**Issue by fjqz177** [antirez/smallchat#24]
I've read several issues and still don't understand how to use it.

**Comment by SaleriHQ** [comment]
You run the executable file, then use `nc localhost 7711` to connect the server

**Comment by Maxwell2020152049** [comment]
Open another terminal, type `nc localhost 7711`, then you will see some prompt information being output.

**Comment by pifeifei** [comment]
![image](https://github.com/antirez/smallchat/assets/45787170/4fbc6ea3-6561-4883-affd-4baedd347983)

成功了， 可以用了
