### ISSUE TITLE
chatMalloc and chatRealloc will probably never fail on Linux, even if memory is full

### ISSUE THREAD

**Issue by kennbr34** [antirez/smallchat#26]
https://github.com/antirez/smallchat/blob/f6c3c9e9becfaadd56916526bb3e1538f29f07a7/smallchat.c#L142

Depending on the configuration of someone's system, Linux will probably over-commit and not make malloc/realloc return a NULL pointer even if memory is full.

The default behavior is to over-commit if the memory request is not "unreasonable". Which basically means any small memory allocation request will return a pointer as if it allocated successfully, but then the program will segfault when trying to write to it, or more likely be killed by the out of memory manager before a write to it is attempted.

There's not really a great platform-independent solution, but I usually read /proc/meminfo and check the CommitLimit to check if an allocation request is too large. Edit: For this particular case, probably best to use MemAvailable

**Comment by antirez** [comment]
In the case of a program like that, the system shouldn't do anything special to detect/handle the OS configuration about overcommitting. It will just go forward depending on what the OS claims to have as free memory. In other systems, like in Redis, I check for the /proc configuration and warn, but there is no point here.
