### ISSUE TITLE
How can it compile on windows?

### ISSUE THREAD

**Issue by monkeywq** [antirez/smallchat#29]
Thanks for your project. It is very nice for junior developers to learn network and C programming.One more question I think it is better if the "smallchat" can run or compile on windows. Because most of our junior developers program on windows ^_^!

**Comment by xiao-yang25** [comment]
One way is to use a virtual machine, of course, if you find it troublesome, you can use an emulated terminal.Here I introduce a tool that I use in practice.

First, you need to download [Cygwin](https://cygwin.com/install.html).

Remember, you need to select additional git，ssh，vim，gcc/make, telnet/netcat or other packages you need during installation, which will be used for compilation and operation later.

Then, fork the code, create ssh key in Cygwin and add it to your github. After that, you can clone it to Cygwin  and create a branch.

Next you can choose to use 'make' or 'gcc smallchat.c -o smallchat` to compile the code.

Finally, open a window first to run `./smallchat`  under  the folder where the executable file is located.Then open two other windows, run `nc localhost 7711`, and use `/nick yourname` to modify the nickname respectively, and now you can speak freely in the chat room.

**Comment by WSEmma** [comment]
Maybe you can simply use WSL! 
https://learn.microsoft.com/en-us/windows/wsl/install

**Comment by monkeywq** [comment]
> One way is to use a virtual machine, of course, if you find it troublesome, you can use an emulated terminal.Here I introduce a tool that I use in practice.
> 
> First, you need to download [Cygwin](https://cygwin.com/install.html).
> 
> Remember, you need to select additional git，ssh，vim，gcc/make, telnet/netcat or other packages you need during installation, which will be used for compilation and operation later.
> 
> Then, fork the code, create ssh key in Cygwin and add it to your github. After that, you can clone it to Cygwin and create a branch.
> 
> Next you can choose to use 'make' or 'gcc smallchat.c -o smallchat` to compile the code.
> 
> Finally, open a window first to run `./smallchat` under the folder where the executable file is located.Then open two other windows, run `nc localhost 7711`, and use `/nick yourname` to modify the nickname respectively, and now you can speak freely in the chat room.

sure，I  have make it successd. Thanks for your recommendation！
