### ISSUE TITLE
This sentence is redundant and can be deleted.

### ISSUE THREAD

**Issue by handsomeZWF** [antirez/smallchat#32]
if (msglen >= (int)sizeof(msg))  msglen = sizeof(msg)-1;

This sentence is redundant and can be deleted.

**Comment by antirez** [comment]
That's not the case. snprintf() return value is the length the string *would have had* if there was enough space.

**Comment by antirez** [comment]
![Screenshot 2023-11-10 at 10 00 45](https://github.com/antirez/smallchat/assets/65632/1453e209-e55a-486a-8800-96e4a971199a)

**Comment by handsomeZWF** [comment]
Thank you.
