### ISSUE TITLE
What about add an open-source license

### ISSUE THREAD

**Issue by mrchipset** [antirez/smallchat#44]
Hi, @antirez.

smallchat is an awesome project. I learned a lot from it.

What about add an exact open-source license to this repo?
I think this will allow people to better learn and participate in this interesting program.

Regards,
Xinfeng

**Comment by ArjixWasTaken** [comment]
Two files so far have licence headers in them, [here](https://github.com/antirez/smallchat/blob/main/smallchat-server.c#L3-L28) and [here](https://github.com/antirez/smallchat/blob/main/smallchat-client.c#L3-L28).

Originally this repository only had one file, now that there are more files the licence is not everywhere.
