### ISSUE TITLE
Unsafe use of return value of snprintf

### ISSUE THREAD

**Issue by ghost** [antirez/smallchat#6]
Unsafe use of return value of snprintf on line 346 can result in out of bounds read when length of nickname + length of name > 254.
https://github.com/antirez/smallchat/blob/main/smallchat.c#L346

> from https://linux.die.net/man/3/snprintf
> If the output was truncated due to this limit then the return value is the number of characters (excluding the terminating null byte) which would have been written to the final string if enough space had been available

Could fix by bounding `msglen` variable to a max value of `256`.

**Comment by antirez** [comment]
Good catch, thank you.
